### ISSUE TITLE
nextPersonFields() could return an object, not array

### ISSUE THREAD

**Issue by witoldsz** [Inbot/inbot-testfixtures#2]
It would be much easier to use, if the `String[] nextPersonFields()` were returning an object with all the properties, instead of an (awkward to use) array…

**Comment by jillesvangurp** [comment]
Yeah, I agree it is a bit ugly. I went for the simplest possible thing that solved my problem. Mostly this feeds into project specific model objects anyway, so it is kind of a transient thing. But from API point of view it would be nicer to have a little Person class. Feel free to add one.
