### ISSUE TITLE
Can we get a reseed method?

### ISSUE THREAD

**Issue by dtashima9** [Inbot/inbot-testfixtures#4]
Would be nice to be able to reseed & shuffle without having to reload the resource (which takes a long time).

The fields are private and not accessible, so it's not possible to extend.

Thanks!

**Comment by jillesvangurp** [comment]
feel free to do a PR. Unfortunately I don't have a lot of time to do work on this project right now.

**Comment by jillesvangurp** [comment]
I spent some time on this today and cut a new release.
